config/routes.rb
ScraperStore::Application.routes.draw do
  resources :statistics

  get "precision_inputs/date_validation", to: "precision_inputs#date_validation"
  get "precision_inputs/time_validation", to: "precision_inputs#time_validation"
  get "precision_inputs/price_validation", to: "precision_inputs#price_validation"
  get "precision_inputs/address_validation", to: "precision_inputs#address_validation"
  resources :precision_inputs
  post "precision_inputs/saveWrong", to: "precision_inputs#saveWrong"
  post "precision_inputs/saveCorrect", to: "precision_inputs#saveCorrect"
  post "precision_inputs/cleanOut", to: "precision_inputs#cleanOut"

  resources :addresses

  resources :events
  post 'events/jsonListener', :as => :allevents
  post 'events/processedJsonListener', :as => :processedEvents

  root "greetings#home"
  get "greetings/howto"
  resources :eventaggs

  post 'eventaggs/sendParserData', :as => :sendParserData

end

app/models/precision_input.rb
class PrecisionInput < ActiveRecord::Base
end

app/controllers/precision_inputs_controller.rb
class PrecisionInputsController < ApplicationController
  before_action :set_precision_input, only: [:show, :edit, :update, :destroy]

  # GET /precision_inputs
  # GET /precision_inputs.json
  def date_validation
    #get a new session_id that is valid
    pastValidHold = PrecisionInput.count(:all, :group => 'session_id')
    if pastValidHold
      if pastValidHold.count()>0
        sessionID = pastValidHold.max[0] + 1
      else
        sessionID = 1
      end
    else
      sessionID = 1
    end
    statID = Statistic.all.pluck(:id).max

    #send a random sample of events and associated precision_inputs



    @validateEvents = Event.all.sample(10)

    @precInputs = []
    @validateEvents.each do |event|
      precinput = PrecisionInput.new
      precinput.event_id = event.id
      precinput.field_name = "pdate"
      precinput.session_id = sessionID
      precinput.statistic_id = statID
      precinput.save
      @precInputs << precinput
    end
  end

  def time_validation
    #get a new session_id that is valid
    pastValidHold = PrecisionInput.count(:all, :group => 'session_id')
    if pastValidHold
      if pastValidHold.count()>0
        sessionID = pastValidHold.max[0] + 1
      else
        sessionID = 1
      end
    else
      sessionID = 1
    end
    statID = Statistic.all.pluck(:id).max

    #send a random sample of events and associated precision_inputs



    @validateEvents = Event.all.sample(10)

    @precInputs = []
    @validateEvents.each do |event|
      precinput = PrecisionInput.new
      precinput.event_id = event.id
      precinput.field_name = "ptime"
      precinput.session_id = sessionID
      precinput.statistic_id = statID
      precinput.save
      @precInputs << precinput
    end
  end

  def price_validation
    #get a new session_id that is valid
    pastValidHold = PrecisionInput.count(:all, :group => 'session_id')
    if pastValidHold
      if pastValidHold.count()>0
        sessionID = pastValidHold.max[0] + 1
      else
        sessionID = 1
      end
    else
      sessionID = 1
    end
    statID = Statistic.all.pluck(:id).max

    #send a random sample of events and associated precision_inputs



    @validateEvents = Event.all.sample(10)

    @precInputs = []
    @validateEvents.each do |event|
      precinput = PrecisionInput.new
      precinput.event_id = event.id
      precinput.field_name = "price"
      precinput.session_id = sessionID
      precinput.statistic_id = statID
      precinput.save
      @precInputs << precinput
    end
  end


  def address_validation
    #get a new session_id that is valid
    pastValidHold = PrecisionInput.count(:all, :group => 'session_id')
    if pastValidHold
      if pastValidHold.count()>0
        sessionID = pastValidHold.max[0] + 1
      else
        sessionID = 1
      end
    else
      sessionID = 1
    end
    statID = Statistic.all.pluck(:id).max

    #send a random sample of events and associated precision_inputs
    @validateEvents = Event.all.sample(10)

    @precInputs = []
    @validateEvents.each do |event|
      precinput = PrecisionInput.new
      precinput.event_id = event.id
      precinput.field_name = "address"
      precinput.session_id = sessionID
      precinput.statistic_id = statID
      precinput.save
      @precInputs << precinput
    end
  end

  def cleanOut
    PrecisionInput.delete_all('is_correct is NULL')
    responseString = '{"outcome":"done"}'
    respond_to do |format|
      format.html { render :html => responseString }
      format.json { render :json => responseString }
    end
  end

  def saveCorrect
    @precision_input = PrecisionInput.find(params[:id])
    @precision_input.is_correct = true

    if @precision_input.save
      responseString = '{"outcome":"saved"}'
    else
      responseString = '{"outcome":"error"}'
    end

    respond_to do |format|
      format.html { render :html => responseString }
      format.json { render :json => responseString }
    end

  end

  def saveWrong
    @precision_input = PrecisionInput.find(params[:id])
    @precision_input.is_correct = false
    @precision_input.how_wrong = params[:precError]

    if @precision_input.save
      responseString = '{"outcome":"saved"}'
    else
      responseString = '{"outcome":"error"}'
    end

    respond_to do |format|
      format.html { render :html => responseString }
      format.json { render :json => responseString }
    end

  end

  def index
    @precision_inputs = PrecisionInput.all
  end

  # GET /precision_inputs/1
  # GET /precision_inputs/1.json
  def show
  end

  # GET /precision_inputs/new
  def new
    @precision_input = PrecisionInput.new
  end

  # GET /precision_inputs/1/edit
  def edit
  end

  # POST /precision_inputs
  # POST /precision_inputs.json
  def create
    @precision_input = PrecisionInput.new(precision_input_params)

    respond_to do |format|
      if @precision_input.save
        format.html { redirect_to @precision_input, notice: 'Precision input was successfully created.' }
        format.json { render action: 'show', status: :created, location: @precision_input }
      else
        format.html { render action: 'new' }
        format.json { render json: @precision_input.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /precision_inputs/1
  # PATCH/PUT /precision_inputs/1.json
  def update
    respond_to do |format|
      if @precision_input.update(precision_input_params)
        format.html { redirect_to @precision_input, notice: 'Precision input was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @precision_input.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /precision_inputs/1
  # DELETE /precision_inputs/1.json
  def destroy
    @precision_input.destroy
    respond_to do |format|
      format.html { redirect_to precision_inputs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_precision_input
      @precision_input = PrecisionInput.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def precision_input_params
      params.require(:precision_input).permit(:session_id, :event_id, :field_name, :is_correct, :how_wrong)
    end
end

app/helpers/precision_inputs_helper.rb
module PrecisionInputsHelper
end

app/views/precision_inputs/_form.html.erb
<%= form_for @precision_input, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :session_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :session_id, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :event_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :event_id, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :field_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :field_name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :is_correct, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :is_correct, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :how_wrong, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :how_wrong, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :statistic_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :statistic_id, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                precision_inputs_path, :class => 'btn' %>
  </div>
<% end %>

app/views/precision_inputs/address_validation.html.erb
<h1>Address Validation</h1>

<% @precInputs.each do |prec| %>
  <% @event = (@validateEvents.select { |sevent| sevent.id == prec.event_id })[0] %>
  <div class="container PrecisionInput" id="<%= 'PrecInContainer' + prec.id.to_s %>">
    <h4><%= @event.name %></h4>
    <strong>Addresses: </strong> <br />
    <% @event.addresses.each do |address| %>
      <span class="precOutput"><%= address.full_address %></span> <br />
    <% end %>
    <br />
    <strong>Event Link: </strong><%= link_to "Click to Navigate to Site", @event.source, target: "_blank" %>
    <br /><br />
    <div class="pull-right" id="<%= 'UserInputter' + prec.id.to_s %>">
      <strong>Describe Error Here:</strong><br />
      <textarea id="<%= 'PrecInError' + prec.id.to_s %>"></textarea><br />
      <button class="btn btn-success" onclick="PrecisionInputCorrect('<%= prec.id %>')">
        This is Right!
      </button>
      <button class="btn btn-warning" onclick="PrecisionError('<%= prec.id %>')">
        This is Wrong!
      </button>
    </div>
  </div>
<% end %>

app/views/precision_inputs/date_validation.html.erb
<h1>Date Validation</h1>

<% @precInputs.each do |prec| %>
  <% @event = (@validateEvents.select { |sevent| sevent.id == prec.event_id })[0] %>
  <div class="container PrecisionInput" id="<%= 'PrecInContainer' + prec.id.to_s %>">
    <h4><%= @event.name %></h4>
    <strong>Date: </strong> 
    <span class="precOutput"><%= @event.pdate %></span>
    <br />
    <strong>Event Link: </strong><%= link_to "Click to Navigate to Site", @event.source, target: "_blank" %>
    <br /><br />
    <div class="pull-right" id="<%= 'UserInputter' + prec.id.to_s %>">
      <strong>Describe Error Here:</strong><br />
      <textarea id="<%= 'PrecInError' + prec.id.to_s %>"></textarea><br />
      <button class="btn btn-success" onclick="PrecisionInputCorrect('<%= prec.id %>')">
        This is Right!
      </button>
      <button class="btn btn-warning" onclick="PrecisionError('<%= prec.id %>')">
        This is Wrong!
      </button>
    </div>
  </div>
<% end %>

app/views/precision_inputs/edit.html.erb
<%- model_class = PrecisionInput -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/precision_inputs/index.html.erb
<ul>
  <li>
    <%= link_to "Check Dates", precision_inputs_date_validation_path %>
  </li>
  <li>
    <%= link_to "Check Times", precision_inputs_time_validation_path %>
  </li>
  <li>
    <%= link_to "Check Addresses", precision_inputs_address_validation_path %>
  </li>
  <li>
    <%= link_to "Check Prices", precision_inputs_price_validation_path %>
  </li>
</ul>

<button class="btn btn-warning" onclick="CleanPrecisionInput()">Clean Out Empty Precision Readings</button>

app/views/precision_inputs/index2.html.erb
<%- model_class = PrecisionInput -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:session_id) %></th>
      <th><%= model_class.human_attribute_name(:event_id) %></th>
      <th><%= model_class.human_attribute_name(:field_name) %></th>
      <th><%= model_class.human_attribute_name(:is_correct) %></th>
      <th><%= model_class.human_attribute_name(:how_wrong) %></th>
      <th><%= model_class.human_attribute_name(:statistic_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @precision_inputs.each do |precision_input| %>
      <tr>
        <td><%= link_to precision_input.id, precision_input_path(precision_input) %></td>
        <td><%= precision_input.session_id %></td>
        <td><%= precision_input.event_id %></td>
        <td><%= precision_input.field_name %></td>
        <td><%= precision_input.is_correct %></td>
        <td><%= precision_input.how_wrong %></td>
        <td><%= precision_input.statistic_id %></td>
        <td><%=l precision_input.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_precision_input_path(precision_input), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      precision_input_path(precision_input),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>



<%= link_to t('.new', :default => t("helpers.links.new")),
            new_precision_input_path,
            :class => 'btn btn-primary' %>

app/views/precision_inputs/new.html.erb
<%- model_class = PrecisionInput -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/precision_inputs/price_validation.html.erb
<h1>Price Validation</h1>

<% @precInputs.each do |prec| %>
  <% @event = (@validateEvents.select { |sevent| sevent.id == prec.event_id })[0] %>
  <div class="container PrecisionInput" id="<%= 'PrecInContainer' + prec.id.to_s %>">
    <h4><%= @event.name %></h4>
    <strong>Price: </strong> 
    <span class="precOutput"><%= @event.price %></span>
    <br />
    <strong>Event Link: </strong><%= link_to "Click to Navigate to Site", @event.source, target: "_blank" %>
    <br /><br />
    <div class="pull-right" id="<%= 'UserInputter' + prec.id.to_s %>">
      <strong>Describe Error Here:</strong><br />
      <textarea id="<%= 'PrecInError' + prec.id.to_s %>"></textarea><br />
      <button class="btn btn-success" onclick="PrecisionInputCorrect('<%= prec.id %>')">
        This is Right!
      </button>
      <button class="btn btn-warning" onclick="PrecisionError('<%= prec.id %>')">
        This is Wrong!
      </button>
    </div>
  </div>
<% end %>

app/views/precision_inputs/show.html.erb
<%- model_class = PrecisionInput -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:session_id) %>:</strong></dt>
  <dd><%= @precision_input.session_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:event_id) %>:</strong></dt>
  <dd><%= @precision_input.event_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:field_name) %>:</strong></dt>
  <dd><%= @precision_input.field_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:is_correct) %>:</strong></dt>
  <dd><%= @precision_input.is_correct %></dd>
  <dt><strong><%= model_class.human_attribute_name(:how_wrong) %>:</strong></dt>
  <dd><%= @precision_input.how_wrong %></dd>
  <dt><strong><%= model_class.human_attribute_name(:statistic_id) %>:</strong></dt>
  <dd><%= @precision_input.statistic_id %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              precision_inputs_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_precision_input_path(@precision_input), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              precision_input_path(@precision_input),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/precision_inputs/time_validation.html.erb
<h1>Time Validation</h1>

<% @precInputs.each do |prec| %>
  <% @event = (@validateEvents.select { |sevent| sevent.id == prec.event_id })[0] %>
  <div class="container PrecisionInput" id="<%= 'PrecInContainer' + prec.id.to_s %>">
    <h4><%= @event.name %></h4>
    <strong>Time: </strong> 
    <span class="precOutput"><%= @event.ptime %></span>
    <br />
    <strong>Event Link: </strong><%= link_to "Click to Navigate to Site", @event.source, target: "_blank" %>
    <br /><br />
    <div class="pull-right" id="<%= 'UserInputter' + prec.id.to_s %>">
      <strong>Describe Error Here:</strong><br />
      <textarea id="<%= 'PrecInError' + prec.id.to_s %>"></textarea><br />
      <button class="btn btn-success" onclick="PrecisionInputCorrect('<%= prec.id %>')">
        This is Right!
      </button>
      <button class="btn btn-warning" onclick="PrecisionError('<%= prec.id %>')">
        This is Wrong!
      </button>
    </div>
  </div>
<% end %>