config/routes.rb
ScraperStore::Application.routes.draw do
  resources :statistics

  get "precision_inputs/date_validation", to: "precision_inputs#date_validation"
  get "precision_inputs/time_validation", to: "precision_inputs#time_validation"
  get "precision_inputs/price_validation", to: "precision_inputs#price_validation"
  get "precision_inputs/address_validation", to: "precision_inputs#address_validation"
  resources :precision_inputs
  post "precision_inputs/saveWrong", to: "precision_inputs#saveWrong"
  post "precision_inputs/saveCorrect", to: "precision_inputs#saveCorrect"
  post "precision_inputs/cleanOut", to: "precision_inputs#cleanOut"

  resources :addresses

  resources :events
  post 'events/jsonListener', :as => :allevents
  post 'events/processedJsonListener', :as => :processedEvents

  root "greetings#home"
  get "greetings/howto"
  resources :eventaggs

  post 'eventaggs/sendParserData', :as => :sendParserData

end

app/models/eventagg.rb
class Eventagg < ActiveRecord::Base
  has_many :xstuffs

  def allTags
    ["eventName_xpath",
    "eventLocation_xpath",
    "eventDateTime_xpath",
    "eventDescription_xpath",
    "eventPrice_xpath",
    "eventImage_xpath"]
  end

  def readableTags
    ["Event Name", 
    "Event Location", 
    "Event Date and Time",
    "Event Description",
    "Event Price",
    "Event Image Src"]
  end

  def event_details
    return EventAgg.where(eventagg_id: self.id)
  end


end

app/controllers/eventaggs_controller.rb
class EventaggsController < ApplicationController
  before_action :set_eventagg, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token, :only => [:sendParserData]
  # GET /eventaggs
  # GET /eventaggs.json

  def sendParserData
    allParsers = params[:parsers]
    successCounter = 0
    totalCounter = 0
    for parser in allParsers
      begin
        sentAgg = Eventagg.new
        sentAgg.is_json = parser["is_json"]
        sentAgg.name = parser["name"]
        sentAgg.link = parser["link"]
        sentAgg.site_type = parser["site_type"]
        sentAgg.domain = parser["domain"]
        sentAgg.pagination_type = parser["pagination_type"]
        sentAgg.eventpage = parser["eventDetailsPageLink_xpath"]
        if sentAgg.save
          successCounter += 1
        end
      rescue
        #do nothing
      ensure
        totalCounter += 1
      end
    end

    responseString = '{"total": "'+totalCounter.to_s+'", "saved":"'+successCounter.to_s+'"}'
    respond_to do |format|
      format.html { render :html => responseString }
      format.json { render :json => responseString }
    end

  end

  def index
    @eventaggs = Eventagg.all

  end

  # GET /eventaggs/1
  # GET /eventaggs/1.json
  def show
  end

  # GET /eventaggs/new
  def new
    @eventagg = Eventagg.new
  end

  # GET /eventaggs/1/edit
  def edit
  end

  # POST /eventaggs
  # POST /eventaggs.json
  def create
    @eventagg = Eventagg.new(eventagg_params)

    respond_to do |format|
      if @eventagg.save
        format.html { redirect_to @eventagg, notice: 'Eventagg was successfully created.' }
        format.json { render action: 'show', status: :created, location: @eventagg }
      else
        format.html { render action: 'new' }
        format.json { render json: @eventagg.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /eventaggs/1
  # PATCH/PUT /eventaggs/1.json
  def update
    respond_to do |format|
      if @eventagg.update(eventagg_params)
        format.html { redirect_to @eventagg, notice: 'Eventagg was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @eventagg.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /eventaggs/1
  # DELETE /eventaggs/1.json
  def destroy
    @eventagg.destroy
    respond_to do |format|
      format.html { redirect_to eventaggs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_eventagg
      @eventagg = Eventagg.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def eventagg_params
      params.require(:eventagg).permit(:name, :link, :site_type, :pagination, :domain, :eventpage)
    end
end

app/helpers/eventaggs_helper.rb
module EventaggsHelper
end

app/views/eventaggs/_form.html.erb
<%= form_for @eventagg, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :link, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :link, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :site_type, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :site_type, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :pagination, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :pagination, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :domain, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :domain, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :eventpage, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :eventpage, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                eventaggs_path, :class => 'btn' %>
  </div>
<% end %>

app/views/eventaggs/edit.html.erb
<%- model_class = Eventagg -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/eventaggs/index.html.erb
<%- model_class = Eventagg -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:site_type) %></th>
      <th><%= model_class.human_attribute_name(:domain) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
    </tr>
  </thead>
  <tbody>
    <% @eventaggs.each do |eventagg| %>
      <tr>
        <td><%= link_to eventagg.name, eventagg_path(eventagg) %></td>
        <td><%= eventagg.site_type %></td>
        <td><%= eventagg.domain %></td>
        <td><%=l eventagg.created_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_eventagg_path,
            :class => 'btn btn-primary' %>

app/views/eventaggs/new.html.erb
<%- model_class = Eventagg -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/eventaggs/show.html.erb
<%- model_class = Eventagg -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @eventagg.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:link) %>:</strong></dt>
  <dd><%= @eventagg.link %></dd>
  <dt><strong><%= model_class.human_attribute_name(:site_type) %>:</strong></dt>
  <dd><%= @eventagg.site_type %></dd>
  <dt><strong><%= model_class.human_attribute_name(:pagination) %>:</strong></dt>
  <dd><%= @eventagg.pagination %></dd>
  <dt><strong><%= model_class.human_attribute_name(:domain) %>:</strong></dt>
  <dd><%= @eventagg.domain %></dd>
  <dt><strong><%= model_class.human_attribute_name(:eventpage) %>:</strong></dt>
  <dd><%= @eventagg.eventpage %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              eventaggs_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_eventagg_path(@eventagg), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              eventagg_path(@eventagg),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>