config/routes.rb
ScraperStore::Application.routes.draw do
  resources :statistics

  get "precision_inputs/date_validation", to: "precision_inputs#date_validation"
  get "precision_inputs/time_validation", to: "precision_inputs#time_validation"
  get "precision_inputs/price_validation", to: "precision_inputs#price_validation"
  get "precision_inputs/address_validation", to: "precision_inputs#address_validation"
  resources :precision_inputs
  post "precision_inputs/saveWrong", to: "precision_inputs#saveWrong"
  post "precision_inputs/saveCorrect", to: "precision_inputs#saveCorrect"
  post "precision_inputs/cleanOut", to: "precision_inputs#cleanOut"

  resources :addresses

  resources :events
  post 'events/jsonListener', :as => :allevents
  post 'events/processedJsonListener', :as => :processedEvents

  root "greetings#home"
  get "greetings/howto"
  resources :eventaggs

  post 'eventaggs/sendParserData', :as => :sendParserData

end

app/models/statistic.rb
class Statistic < ActiveRecord::Base
  def getPrecision(fname)
    selectStatement = """SELECT count(p.id) as numSamples,
                          sum(case when p.is_correct='t' then 1 else 0 end) as numCorrect, 
                          sum(case when p.is_correct='f' then 1 else 0 end) as numWrong, 
                          avg(case when p.is_correct='t' then 1 else 0 end) as percWrong, 
                          p.session_id as session_id
                        FROM precision_inputs as p 
                        WHERE p.statistic_id=#{self.id} and p.field_name='#{fname}' and (p.is_correct is not NULL)
                        Group By p.session_id"""

    precInputs = PrecisionInput.select("count(p.id) as numSamples", )
    precInputs = PrecisionInput.find_by_sql(selectStatement).delete_if {|item| (item['numSamples'].nil? or item["numSamples"]<10)}

    if precInputs
      return precInputs
    else
      return []
    end
  end

end

app/controllers/statistics_controller.rb
class StatisticsController < ApplicationController
  before_action :set_statistic, only: [:show, :edit, :update, :destroy]

  # GET /statistics
  # GET /statistics.json
  def index
    @statistics = Statistic.all.order("id DESC")
  end

  # GET /statistics/1
  # GET /statistics/1.json
  def show
  end

  # GET /statistics/new
  def new
    @statistic = Statistic.new
  end

  # GET /statistics/1/edit
  def edit
  end

  # POST /statistics
  # POST /statistics.json
  def create
    @statistic = Statistic.new(statistic_params)

    respond_to do |format|
      if @statistic.save
        format.html { redirect_to @statistic, notice: 'Statistic was successfully created.' }
        format.json { render action: 'show', status: :created, location: @statistic }
      else
        format.html { render action: 'new' }
        format.json { render json: @statistic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statistics/1
  # PATCH/PUT /statistics/1.json
  def update
    respond_to do |format|
      if @statistic.update(statistic_params)
        format.html { redirect_to @statistic, notice: 'Statistic was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @statistic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statistics/1
  # DELETE /statistics/1.json
  def destroy
    @statistic.destroy
    respond_to do |format|
      format.html { redirect_to statistics_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_statistic
      @statistic = Statistic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def statistic_params
      params.require(:statistic).permit(:total_events, :num_addresses, :num_pdate, :num_ptime, :num_price)
    end
end

app/helpers/statistics_helper.rb
module StatisticsHelper
end

app/views/statistics/_form.html.erb
<%= form_for @statistic, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :total_events, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :total_events, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :num_addresses, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :num_addresses, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :num_pdate, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :num_pdate, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :num_ptime, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :num_ptime, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :num_price, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :num_price, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                statistics_path, :class => 'btn' %>
  </div>
<% end %>

app/views/statistics/edit.html.erb
<%- model_class = Statistic -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/statistics/index.html.erb
<%- model_class = Statistic -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:num_sent) %></th>
      <th><%= model_class.human_attribute_name(:total_events) %></th>
      <th><%= model_class.human_attribute_name(:num_addresses) %></th>
      <th><%= model_class.human_attribute_name(:num_pdate) %></th>
      <th><%= model_class.human_attribute_name(:num_ptime) %></th>
      <th><%= model_class.human_attribute_name(:num_price) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @statistics.each do |statistic| %>
      <tr>
        <td><%= link_to statistic.id, statistic_path(statistic) %></td>
        <td><%= statistic.num_sent %></td>
        <td><%= statistic.total_events %></td>
        <td>
          <%= statistic.num_addresses %>
          <% statistic.getPrecision('address').each do |prec| %>
            <br />------<br />
            <%= "Num Samples: #{prec['numSamples']}, Right: #{prec['numCorrect']}, Wrong: #{prec['numWrong']}, Percentage: #{prec['percWrong']*100}%" %>
          <% end %>
        </td>
        <td>
          <%= statistic.num_pdate %>
          <% statistic.getPrecision('pdate').each do |prec| %>
            <br />------<br />
            <%= "Num Samples: #{prec['numSamples']}, Right: #{prec['numCorrect']}, Wrong: #{prec['numWrong']}, Percentage: #{prec['percWrong']*100}%" %>
          <% end %>
        </td>
        <td>
          <%= statistic.num_ptime %>
          <% statistic.getPrecision('ptime').each do |prec| %>
            <br />------<br />
            <%= "Num Samples: #{prec['numSamples']}, Right: #{prec['numCorrect']}, Wrong: #{prec['numWrong']}, Percentage: #{prec['percWrong']*100}%" %>
          <% end %>
        </td>
        <td>
          <%= statistic.num_price %>
          <% statistic.getPrecision('price').each do |prec| %>
            <br />------<br />
            <%= "Num Samples: #{prec['numSamples']}, Right: #{prec['numCorrect']}, Wrong: #{prec['numWrong']}, Percentage: #{prec['percWrong']*100}%" %>
          <% end %>
        </td>
        <td><%= statistic.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_statistic_path(statistic), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      statistic_path(statistic),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_statistic_path,
            :class => 'btn btn-primary' %>

app/views/statistics/new.html.erb
<%- model_class = Statistic -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/statistics/show.html.erb
<%- model_class = Statistic -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:total_events) %>:</strong></dt>
  <dd><%= @statistic.total_events %></dd>
  <dt><strong><%= model_class.human_attribute_name(:num_addresses) %>:</strong></dt>
  <dd><%= @statistic.num_addresses %></dd>
  <dt><strong><%= model_class.human_attribute_name(:num_pdate) %>:</strong></dt>
  <dd><%= @statistic.num_pdate %></dd>
  <dt><strong><%= model_class.human_attribute_name(:num_ptime) %>:</strong></dt>
  <dd><%= @statistic.num_ptime %></dd>
  <dt><strong><%= model_class.human_attribute_name(:num_price) %>:</strong></dt>
  <dd><%= @statistic.num_price %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              statistics_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_statistic_path(@statistic), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              statistic_path(@statistic),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>