config/routes.rb
ScraperStore::Application.routes.draw do
  resources :statistics

  get "precision_inputs/date_validation", to: "precision_inputs#date_validation"
  get "precision_inputs/time_validation", to: "precision_inputs#time_validation"
  get "precision_inputs/price_validation", to: "precision_inputs#price_validation"
  get "precision_inputs/address_validation", to: "precision_inputs#address_validation"
  resources :precision_inputs
  post "precision_inputs/saveWrong", to: "precision_inputs#saveWrong"
  post "precision_inputs/saveCorrect", to: "precision_inputs#saveCorrect"
  post "precision_inputs/cleanOut", to: "precision_inputs#cleanOut"

  resources :addresses

  resources :events
  post 'events/jsonListener', :as => :allevents
  post 'events/processedJsonListener', :as => :processedEvents

  root "greetings#home"
  get "greetings/howto"
  resources :eventaggs

  post 'eventaggs/sendParserData', :as => :sendParserData

end

app/models/event.rb
class Event < ActiveRecord::Base

  def addresses
    addresses = Address.where(["event_id = ?", self.id])
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token, :only => [:jsonListener, :processedJsonListener]

  # GET /events
  # GET /events.json

  def processedJsonListener
    allEvents = params[:event]
    eventCounter = 0
    saveCounter = 0
    Event.delete_all
    Address.delete_all
    EventDateTime.delete_all

    for event in allEvents
      begin
        newevent = Event.new
        newevent.name = nil_or_string(event[:name])
        newevent.description = nil_or_string(event[:description])
        newevent.imagepath = nil_or_string(event[:imagePath])
        newevent.source = nil_or_string(event[:source])
        newevent.location = nil_or_string(event[:location])
        newevent.datetime = nil_or_string(event[:datetime])

        #newevent.dump = nil_or_string(event[:dump])

        newevent.price = flatten(event[:pPrice])
        newevent.ptime = flatten(event[:time])
        newevent.pdate = flatten(event[:date])

        if newevent.save
          saveCounter+=1
          if event[:addresses][:addresses] != nil and event[:addresses][:addresses].count > 0
            for address in event[:addresses][:addresses]
              newaddy = Address.new
              newaddy.event_id = newevent.id
              newaddy.full_address = nil_or_string(address[:full_address])
              newaddy.city = nil_or_string(address[:city])
              newaddy.region = nil_or_string(address[:region1])

              newaddy.save
            end
          end
          if event[:datetime_structs] != nil and event[:datetime_structs].count > 0
            for datetime in event[:datetime_structs]
              eventDate = EventDateTime.new
              eventDate.event_id = newevent.id
              eventDate = setDateTime(eventDate, datetime[:date][:start_date][:full_date], datetime[:time][:start_time], nil_or_string(datetime[:time][:end_time]))
              eventDate.save


              if datetime[:date][:end_date] != nil and nil_or_string(datetime[:date][:end_date][:full_date]) != nil
                startDate = DateTime.parse(datetime[:date][:start_date][:full_date])
                endDate = DateTime.parse(datetime[:date][:end_date][:full_date])
                endInt = endDate.to_time.to_i
                currDate = startDate+1
                currDateInt = currDate.to_time.to_i
                while currDateInt <= endInt do
                  eventDate = EventDateTime.new
                  eventDate.event_id = newevent.id
                  eventDate = setDateTime(eventDate, currDate, datetime[:time][:start_time], nil_or_string(datetime[:time][:end_time]))
                  eventDate.save
                  currDate = currDate + 1
                  currDateInt = currDate.to_time.to_i
                end
              end
            end
          end
        end

      rescue
        #do nothing
      ensure
        eventCounter+=1
      end
    end

    statistic = Statistic.new
    statistic.num_sent = eventCounter
    statistic.total_events = saveCounter
    statistic.num_addresses = (Address.count(:all, :group => :event_id)).count()
    
    statsAllEvents = Event.all
    
    statistic.num_pdate = clean_and_count(statsAllEvents.pluck(:pdate))
    statistic.num_ptime = clean_and_count(statsAllEvents.pluck(:ptime))
    statistic.num_price = clean_and_count(statsAllEvents.pluck(:price))
    statistic.save()

    responseString = '{"total": "'+eventCounter.to_s+'", "saved":"'+saveCounter.to_s+'"}'
    respond_to do |format|
        format.html { render :html => responseString }
        format.json { render :json => responseString }
      
    end
  end

  def jsonListener
    allEvents = params[:event]
    eventCounter = 0
    saveCounter = 0

    for event in allEvents
      begin
        newevent = Event.new
        newevent.name = event[:name]
        newevent.location = event[:location]
        newevent.description = event[:description]
        newevent.datetime = event[:datetime]
        newevent.price = event[:price]
        newevent.imagepath = event[:imagePath]
        newevent.save
        saveCounter += 1
      rescue
        #do nothing
      ensure
        eventCounter += 1
      end
    end
    responseString = '{"total": "'+eventCounter.to_s+'", "saved":"'+saveCounter.to_s+'"}'
    respond_to do |format|
        format.html { render :html => responseString }
        format.json { render :json => responseString }
    end
  end




  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render action: 'show', status: :created, location: @event }
      else
        format.html { render action: 'new' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :location, :description, :datetime, :price, :imagepath, :pdate, :ptime, :dump)
    end

    def clean_and_count(sentArray)
      sentArray.delete_if { |item| my_remove(item, ",.|\t\n\r").blank? }

      return sentArray.count
    end

    def my_remove(sentString, delims)
      returnString = sentString
      if returnString
        delims.split("").each do |delim|
          hold = returnString.slice!(delim.to_s)
        end
      else
        returnString = ""
      end
      return returnString
    end

    def flatten(sentArray)
      str = ""
      if sentArray and sentArray.count>0
        for item in sentArray
          str += item + " | "
        end
      else
        str = nil
      end
      return str
    end

    def nil_or_string(sentString)
      if sentString
        sentString = sentString.strip()
        if sentString == nil or sentString == ""
          return nil
        else
          return sentString
        end
      else
        return nil
      end
    end

    def setDateTime(dtObj, writeDate, startTime, endTime)
      dtString = writeDate+" " + startTime
      dtObj.start = DateTime.parse(dtString)

      if endTime != nil
        dtString = writeDate+" " + endTime
        dtObj.end = DateTime.parse(dtString)
      else
        dtString = writeDate+" 11:59:59 pm"
        dtObj.end = DateTime.parse(dtString)
      end
      return dtObj

    end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for @event, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :location, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :location, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :description, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :datetime, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :datetime, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :price, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :price, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :imagepath, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :imagepath, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :pdate, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :pdate, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :ptime, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :ptime, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :dump, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :dump, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                events_path, :class => 'btn' %>
  </div>
<% end %>

app/views/events/edit.html.erb
<%- model_class = Event -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/events/index.html.erb
<%- model_class = Event -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:imagepath) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:location) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:datetime) %></th>
      <th><%= model_class.human_attribute_name(:price) %></th>
      <th><%= model_class.human_attribute_name(:pdate) %></th>
      <th><%= model_class.human_attribute_name(:ptime) %></th>
      <th><%= model_class.human_attribute_name(:source) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= link_to event.id, event_path(event) %></td>
        <td>
          <%= image_tag(event.imagepath, size:"32", alt: "Event Image")%>
        </td>
        <td><%= event.name %></td>
        <td><%= event.location %></td>
        <td><%= event.description %></td>
        <td><%= event.datetime %></td>
        <td><%= event.price %></td>
        <td><%= event.pdate %></td>
        <td><%= event.ptime %></td>
        <td>
          <%= link_to "Event Link", event.source %>
        </td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_event_path(event), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      event_path(event),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_event_path,
            :class => 'btn btn-primary' %>

app/views/events/new.html.erb
<%- model_class = Event -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/events/show.html.erb
<%- model_class = Event -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              events_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_event_path(@event), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              event_path(@event),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @event.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:location) %>:</strong></dt>
  <dd><%= @event.location %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @event.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:datetime) %>:</strong></dt>
  <dd><%= @event.datetime %></dd>
  <dt><strong><%= model_class.human_attribute_name(:price) %>:</strong></dt>
  <dd><%= @event.price %></dd>
  <dt><strong><%= model_class.human_attribute_name(:imagepath) %>:</strong></dt>
  <dd><%= @event.imagepath %></dd>
  <dt><strong><%= model_class.human_attribute_name(:pdate) %>:</strong></dt>
  <dd><%= @event.pdate %></dd>
  <dt><strong><%= model_class.human_attribute_name(:ptime) %>:</strong></dt>
  <dd><%= @event.ptime %></dd>
  <dt><strong><%= model_class.human_attribute_name(:dump) %>:</strong></dt>
  <dd><%= @event.dump %></dd>
</dl>

<IFRAME src="<%= @event.source %>" width="100%" height="1000"/>